server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: 'health,info'

springdoc:
  swagger-ui:
    disable-swagger-default-url: 'true'
    path: '/swagger-ui'

helloPattern: "Hello, %s!"

spring:
  datasource:
    password: ${database.password}
    driver-class-name: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://192.168.3.187:5432/arachni
    username: app_tuz
  liquibase:
    enabled: 'false'